# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
# name: Deploy VitePress site to Pages

# on:
#   push:
#     tags:
#       - '*'

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

name: Deploy VitePress site to Pages

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Install yarn
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Site
        run: npm run docs:build

      - name: Deploy for Gitee 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
          # enable single-commit to reduce the repo size
          single-commit: true
          clean: true